"""Abstract strategy interface and Signal data model."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from decimal import Decimal
from typing import TYPE_CHECKING

from ..models.order import OrderAction, OrderSide

if TYPE_CHECKING:
    from ..client.rest import KalshiRestClient
    from ..models.market import Market


@dataclass
class Signal:
    """A trading signal generated by a strategy.

    Represents a recommended trade with edge analysis.
    """
    ticker: str
    side: OrderSide           # YES or NO
    action: OrderAction       # BUY or SELL
    target_price: Decimal     # Price to bid/ask
    edge: Decimal             # Expected edge (positive = profitable)
    confidence: float         # 0.0 to 1.0
    strategy_name: str        # Which strategy generated this
    reason: str               # Human-readable explanation
    is_arbitrage: bool = False  # Part of an arb pair
    pair_id: str = ""          # Links paired arb signals together

    @property
    def expected_value(self) -> Decimal:
        """Expected dollar profit per contract."""
        if self.action == OrderAction.BUY:
            # Profit if winning = 1.00 - price, probability of winning = price + edge
            fair_prob = self.target_price + self.edge
            return fair_prob * (Decimal("1.00") - self.target_price) - (
                (1 - fair_prob) * self.target_price
            )
        return self.edge  # Simplified for sells

    def __repr__(self) -> str:
        return (
            f"Signal({self.strategy_name}: {self.action.value} "
            f"{self.side.value} {self.ticker} @ ${self.target_price} "
            f"edge={self.edge:.4f} conf={self.confidence:.2f} "
            f"| {self.reason})"
        )


class Strategy(ABC):
    """Abstract base class for trading strategies.

    All strategies must implement:
    - scan(): analyze markets and return trading signals
    - name: human-readable strategy name
    """

    @abstractmethod
    def scan(
        self,
        markets: list[Market],
        client: KalshiRestClient,
    ) -> list[Signal]:
        """Scan markets and return trading signals.

        Args:
            markets: List of currently open markets
            client: API client for fetching additional data (orderbooks, etc.)

        Returns:
            List of Signal objects representing recommended trades
        """
        pass

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable strategy name."""
        pass
